### ISSUE TITLE
Posting my comment here since you locked me out of: https://github.com/michaelklishin/neocons/issues/80

### ISSUE THREAD

**Issue by johanatan** [michaelklishin/neocons#81]
RE: https://github.com/michaelklishin/neocons/issues/80

a) Perhaps you misunderstood the suggestion if you think that this vastly increases your surface area to maintain. If you make the entire library batch-friendly then you have exactly one set of [batch-friendly] APIs to maintain. I can understand why you would push back against this as it is likely a massive refactoring given your extant coding style and perhaps the elegant solution is beyond your current capabilities. (There are clever ways to add this feature more easily though-- most likely using macros to automate Continuation Passing Style to emulate something like Scala's "for comprehensions" [or F#'s "computation expressions"] inside `with-batch` or `with-transaction` blocks).

b) Regarding whether I will "be around to maintain it" or not. My GitHub account @johanatan is the only GitHub account I've ever owned and is the only account I ever plan to own. I can always be reached there. I can also of course give you other ways to reach me if you would like. But this is really beside the point-- if the software is written correctly, then "maintenance" should be rather trivial to begin with and anyone can carry it out.

Would you like to see a pull request illustrating the addition of this feature with a minimal change to the code? Depending on my business unit's decision regarding this issue, I may be able to spend my time developing that pull request for you.

**Comment by michaelklishin** [comment]
@johanatan we will consider a pull request.

Maintaining an open source project is more than maintaining code. It involves things like:

 * Ensuring every API variation or scenario is decently covered with tests.
 * Ensuring every API variation is documented.
 * Answering questions.
 * Constantly looking for inconsistencies in API variations

and so on. Elastisch's ~ 4 years of history suggest that there will be users who only contibute a feature to one API but not the other, or do a quick-and-dirty attempt at updating both. Resolving the resulting
mess is *always* up to the maintainer.

We can @-mention every Neocons contributor on GitHub but that absolutely does not mean they will spend any time maintaining their code, leave alone helping with tests and docs: a year or two down the road, they may or may not be using Clojure or Neo4J or Neocons to begin with, leave alone have the time or interest to help. So yes, we (or any other project maintainer) must assume it will all be on us. Any other assumption would be naive and not very responsible at best.

I'm going to unlock #80 but remain unconvinced that it's such a big deal. I also have little motivation to work with @johanatan on resolving it because his activity on both GitHub and Twitter suggests he has 0 respect to the maintainers of projects he uses. But @ducky427 may feel otherwise.
